### ISSUE TITLE
TokenJar does not renew tokens in intruder with multiple threads

### ISSUE THREAD

**Issue by 0xams** [DanNegrea/TokenJar#14]
Hello
when testing in application that generates a new token for Post requests from previous GET request, token jar seems to be able to get new tokens on the repeater, however in intruder only if you set it to one thread at a time.
if you leave it to the 10 threads default, only one request will get a valid token, the rest will not be valid as they are using the same token as the first one.
so out of 20 requests 2 will be valid and 18 will not..etc
it seems it's taking the number of threads (10 as the default) and treating all of them as one request and assigning them one token only.

any way of modifying token jar so each thread is considered a separate request and gets it's own token?

**Comment by DanNegrea** [comment]
Hi,
What is the behavior of the application/page/request that you are testing? 

A. Does each request (not page) make use of a new token? In this case it would be hard to use multi-thread since the TokenJar as well as the build-in CookieJar cannot distinguish between threads (technical almost impossible because of the API). In this case you should scan with only one tread (or in extreme cases with multiple instances of Burp still with on thread). 

B. Does each page make use of a unique token (same token valid for multiple requests that originate from that page) then this should work with multi-treads. If it doesn't work then that is a bug. 

To understand the behavior you can use the debug feature from TokenJar window and follow the messages in Extender > Extensions > TokenJar > Output. 

Let me know what you find out!

**Comment by DanNegrea** [comment]
Did you managed to capture more details?

**Comment by 0xams** [comment]
It works with one request at a time...its just when its 10 threads, inly
one will work and the others will be invalid because they are using the
same token which became invalid after the first thread used it.

**Comment by DanNegrea** [comment]
I will close the issue, since there is nothing I could do. It is a limitation that is affecting both TokenJar and CookieJar.  Thanks for feedback.
