### ISSUE TITLE
Dynamic parameter names

### ISSUE THREAD

**Issue by Hipapheralkus** [DanNegrea/TokenJar#6]
Hi,
Nice improvements for version 2:) I have a feature request - I'm working in an environment, where there are many parameter names which have dynamic value. The value is returned in the response, so it would be perfect if I could set up the extension to work not only with parameter values, but also parameter names.

For example, Burp does not provide this by native functionality, and I could use a very complex setup of Custom Parameter Handler, but this extension is much better for my usecase. Is there a chance it could be implemented?:) It could be a different checkbox (like you added Header recently), having regexp group in the Name, and the value would be parsed like usual. Ideally, a possibility of chaining the dynamic parameter name + value would be great to have, so evaluate two regexp groups in a single record.
My usecase is for example:
`&_somePortlet_WAR_somePortlet_INSTANCE_650TXgMWET8v_link_id=64ac0029-acf6-46c9-cc62-ce0cc646675d&`, where you can see the INSTANCE_ID being dynamic name of the parameter; followed by regular value.
Many thanks for considering this, I think it would be an amazing improvement:)

**Comment by DanNegrea** [comment]
Hi, 

This feature was on my list for a long time. In TokenJar it would take a tremendous energy to implement it because of how I designed it from the start. 
The focus was on performance, because of heavy testing that took weeks. Technically name is used as a entry in a Hashtable. With a dynamic names this design will no longer work. 

This is why I added a new extension: https://github.com/DanNegrea/PyRules 
Please use the other extension, which, by the way, is also user friendly and allows you to save the configuration in plain text.

If you need help post there a new message. 

Best Regards,
Dan
